Add showcase and gen9 badges to player table
UnownHash/Golbat pull request #146
Opened 2023-08-14 18:12 UTC by na-ji

Hello,

I've added two new columns on the player table. However:
- ~Gen9 is not enabled yet, but will probably be in september.~ It's now enabled
- Showcase badge seems to only be for max size showcases. They might add more badges later. 
- Route badges that were unused are still unused now. So I removed the comments. 
- Route stats are in another proto which isn't available in the public profile.

2023-08-18 07:23 UTC, na-ji commented
Timing is right since Niantic just enabled the gen 9 badge 

![image](https://github.com/UnownHash/Golbat/assets/757637/381417bf-2811-4fe4-98f0-195a52b51e29)

2023-08-18 07:29 UTC, Fabio1988 approved these changes

2023-08-18 09:45 UTC, jfberry commented
Migration 21 already in use, so this needs changing to 22; otherwise happy [or we could merge legacy stats at 22 and make this 23 - happy for either order]

2023-08-19 06:51 UTC, Fabio1988 requested changes
@na-ji pls rename migration due to merge of https://github.com/UnownHash/Golbat/pull/143

Use `23_xxxx`

2023-08-19 11:48 UTC, Fabio1988 approved these changes
I assume you tested already? Code looks good, migration now as well, lgtm

2023-08-20 13:00 UTC, na-ji commented
> I assume you tested already? Code looks good, migration now as well, lgtm

Yes, I now have both the gen 9 values and the showcase. 

<img width="500" alt="image" src="https://github.com/UnownHash/Golbat/assets/757637/5cf445b1-3a7b-4662-acdb-d603bf14e6bb">

2023-08-20 13:13 UTC, jfberry approved these changes

2023-08-20 13:14 UTC, merged